## IMPORTAR LIBRERIAS

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from dotenv import load_dotenv
import os
from pathlib import Path
import openpyxl
import sqlalchemy as sa

# Desactivar notación científica
pd.set_option('display.float_format', lambda x: '%.3f' % x)
np.set_printoptions(suppress=True)

# Cargar variables de entorno
load_dotenv()

print("✅ Librerías importadas correctamente")

✅ Librerías importadas correctamente

Cargar los datos.

In [2]:
datos = pd.read_csv('../02_datos/01_Originales/prestamos.csv')
datos.head()

,id_cliente,empleo,antigüedad_empleo,ingresos,ingresos_verificados,rating,dti,vivienda,num_hipotecas,num_lineas_credito,...,id_prestamo,descripcion,finalidad,principal,tipo_interes,num_cuotas,imp_cuota,imp_amortizado,estado,imp_recuperado
0,137387967,Hvac technician,3 years,54000.000,Source Verified,A,19.310,MORTGAGE,2.000,10.000,...,NaN,NaN,debt_consolidation,15000.000,7.210,36 months,464.600,2669.060,Current,0.000
1,4798121,"Target Promotions and Marketing,Inc",10+ years,65000.000,Not Verified,D,25.400,RENT,1.000,15.000,...,NaN,NaN,debt_consolidation,10000.000,17.770,36 months,360.380,6362.960,Charged Off,0.000
2,46641215,Banker,5 years,135000.000,Verified,A,14.680,RENT,0.000,19.000,...,NaN,NaN,debt_consolidation,24000.000,6.390,36 months,734.380,24000.000,Fully Paid,0.000
3,87998444,executive director,9 years,188000.000,Source Verified,B,11.690,MORTGAGE,3.000,15.000,...,NaN,NaN,credit_card,27000.000,8.990,60 months,560.350,12443.000,Current,0.000
4,132883631,Subsea Technician,7 years,125000.000,Source Verified,B,9.000,MORTGAGE,1.000,6.000,...,NaN,NaN,debt_consolidation,22000.000,10.900,36 months,719.220,22000.000,Fully Paid,0.000

### Extraer y reservar el dataset de validación

In [10]:
val= datos.sample(frac = 0.3)
val.head()

,id_cliente,empleo,antigüedad_empleo,ingresos,ingresos_verificados,rating,dti,vivienda,num_hipotecas,num_lineas_credito,...,id_prestamo,descripcion,finalidad,principal,tipo_interes,num_cuotas,imp_cuota,imp_amortizado,estado,imp_recuperado
91384,7730314,Electrical Design Engineer - Teleworker,7 years,95000.000,Verified,C,17.280,MORTGAGE,2.000,13.000,...,NaN,Borrower added on 10/08/13 > Looking to cons...,debt_consolidation,24000.000,16.200,36 months,846.150,24000.000,Fully Paid,0.000
84143,127564181,Account Manager,1 year,50000.000,Verified,C,25.560,MORTGAGE,3.000,9.000,...,NaN,NaN,debt_consolidation,5000.000,14.080,36 months,171.090,1568.600,Current,0.000
35955,11926289,director,< 1 year,63000.000,Verified,B,19.300,MORTGAGE,1.000,9.000,...,NaN,Borrower added on 02/18/14 > Refinance of hi...,credit_card,10500.000,10.990,36 months,343.710,10500.000,Fully Paid,0.000
83527,91634492,Operations Manager,5 years,62000.000,Not Verified,C,8.820,RENT,0.000,4.000,...,NaN,NaN,debt_consolidation,15550.000,12.740,36 months,522.000,13106.770,Current,0.000
11385,56059699,Cage Shift Supervisor,1 year,50000.000,Source Verified,C,24.870,RENT,0.000,14.000,...,NaN,NaN,debt_consolidation,12000.000,12.690,36 months,402.540,12000.000,Fully Paid,0.000

In [11]:
val.to_pickle('../02_datos//02_Validacion/validacion.pkl')

### Extraer y guardar el dataset de trabajo

In [12]:
trabajo = datos.loc[~datos.index.isin(val.index)]

In [ ]:
trabajo.to_pickle('../02_datos/03_Entrenamiento/train.pkl')

In [14]:
datos.shape

(200000, 25)

In [15]:
trabajo.shape

(140000, 25)

In [16]:
val.shape

(60000, 25)