# CALIDAD DE DATOS

## IMPORTAR PAQUETES

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from dotenv import load_dotenv
import os
from pathlib import Path
import openpyxl
import sqlalchemy as sa

# Desactivar notación científica
pd.set_option('display.float_format', lambda x: '%.3f' % x)
np.set_printoptions(suppress=True)

# Cargar variables de entorno
load_dotenv()

print("✅ Librerías importadas correctamente")

✅ Librerías importadas correctamente

## IMPORTAR LOS DATOS

In [2]:
df = pd.read_pickle('../02_datos/03_Entrenamiento/train.pkl')
df

,id_cliente,empleo,antigüedad_empleo,ingresos,ingresos_verificados,rating,dti,vivienda,num_hipotecas,num_lineas_credito,...,id_prestamo,descripcion,finalidad,principal,tipo_interes,num_cuotas,imp_cuota,imp_amortizado,estado,imp_recuperado
1,4798121,"Target Promotions and Marketing,Inc",10+ years,65000.000,Not Verified,D,25.400,RENT,1.000,15.000,...,NaN,NaN,debt_consolidation,10000.000,17.770,36 months,360.380,6362.960,Charged Off,0.000
2,46641215,Banker,5 years,135000.000,Verified,A,14.680,RENT,0.000,19.000,...,NaN,NaN,debt_consolidation,24000.000,6.390,36 months,734.380,24000.000,Fully Paid,0.000
4,132883631,Subsea Technician,7 years,125000.000,Source Verified,B,9.000,MORTGAGE,1.000,6.000,...,NaN,NaN,debt_consolidation,22000.000,10.900,36 months,719.220,22000.000,Fully Paid,0.000
5,131289518,NaN,10+ years,72777.000,Source Verified,D,24.740,MORTGAGE,2.000,10.000,...,NaN,NaN,home_improvement,25000.000,21.850,60 months,688.350,2811.270,Current,0.000
6,77861711,Correctional officer,10+ years,50000.000,Verified,C,29.310,MORTGAGE,1.000,8.000,...,NaN,NaN,debt_consolidation,14400.000,15.310,36 months,501.370,2310.490,Charged Off,6430.360
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199994,119242742,NaN,NaN,20000.000,Source Verified,C,8.020,RENT,0.000,5.000,...,NaN,NaN,debt_consolidation,2500.000,12.620,36 months,83.780,996.060,Late (31-120 days),0.000
199996,121031962,Owner & President,6 years,111697.000,Verified,B,16.630,MORTGAGE,2.000,10.000,...,NaN,NaN,other,10000.000,9.440,36 months,320.050,4388.510,Current,0.000
199997,135641397,Sr. Field Engineer,10+ years,285000.000,Source Verified,D,6.020,MORTGAGE,3.000,9.000,...,NaN,NaN,small_business,30000.000,17.470,36 months,1076.620,5387.530,Current,0.000
199998,53664762,Attorney,8 years,168000.000,Source Verified,E,4.690,RENT,0.000,8.000,...,NaN,NaN,small_business,30050.000,18.250,60 months,767.170,2964.440,Charged Off,2750.880
199999,94394801,NaN,NaN,80000.000,Not Verified,C,31.490,MORTGAGE,1.000,9.000,...,NaN,NaN,debt_consolidation,10000.000,13.990,36 months,341.730,7096.400,Current,0.000

In [3]:
# Eliminar el índice del DataFrame
df.reset_index(drop=True, inplace=True)

## VISIÓN GENERAL

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140000 entries, 0 to 139999
Data columns (total 25 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id_cliente                   140000 non-null  int64
 1   empleo                       129739 non-null  object
 2   antigüedad_empleo            130968 non-null  object
 3   ingresos                     140000 non-null  float64
 4   ingresos_verificados         140000 non-null  object
 5   rating                       140000 non-null  object
 6   dti                          139894 non-null  float64
 7   vivienda                     140000 non-null  object
 8   num_hipotecas                136949 non-null  float64
 9   num_lineas_credito           139998 non-null  float64
 10  porc_tarjetas_75p            135394 non-null  float64
 11  porc_uso_revolving           139899 non-null  float64
 12  num_cancelaciones_12meses    139992 non-null  float64
 13  num_derogatorios             139998 non-null  float64
 14  num_meses_desde_ult_retraso  67993 non-null   float64
 15  id_prestamo                  0 non-null       float64
 16  descripcion                  7761 non-null    object
 17  finalidad                    140000 non-null  object
 18  principal                    140000 non-null  float64
 19  tipo_interes                 140000 non-null  float64
 20  num_cuotas                   140000 non-null  object
 21  imp_cuota                    140000 non-null  float64
 22  imp_amortizado               140000 non-null  float64
 23  estado                       140000 non-null  object
 24  imp_recuperado               140000 non-null  float64
dtypes: float64(15), int64(1), object(9)
memory usage: 26.7+ MB

## TIPOS DE DATOS

### Identificación

In [5]:
df.head().T

,0,1,2,3,4
id_cliente,4798121,46641215,132883631,131289518,77861711
empleo,"Target Promotions and Marketing,Inc",Banker,Subsea Technician,NaN,Correctional officer
antigüedad_empleo,10+ years,5 years,7 years,10+ years,10+ years
ingresos,65000.000,135000.000,125000.000,72777.000,50000.000
ingresos_verificados,Not Verified,Verified,Source Verified,Source Verified,Verified
rating,D,A,B,D,C
dti,25.400,14.680,9.000,24.740,29.310
vivienda,RENT,RENT,MORTGAGE,MORTGAGE,MORTGAGE
num_hipotecas,1.000,0.000,1.000,2.000,1.000
num_lineas_credito,15.000,19.000,6.000,10.000,8.000
porc_tarjetas_75p,85.700,0.000,33.300,33.300,0.000
porc_uso_revolving,86.200,16.300,69.900,63.200,40.800
num_cancelaciones_12meses,0.000,0.000,0.000,0.000,0.000
num_derogatorios,0.000,0.000,0.000,0.000,0.000
num_meses_desde_ult_retraso,NaN,NaN,16.000,NaN,8.000
id_prestamo,NaN,NaN,NaN,NaN,NaN
descripcion,NaN,NaN,NaN,NaN,NaN
finalidad,debt_consolidation,debt_consolidation,debt_consolidation,home_improvement,debt_consolidation
principal,10000.000,24000.000,22000.000,25000.000,14400.000
tipo_interes,17.770,6.390,10.900,21.850,15.310
num_cuotas,36 months,36 months,36 months,60 months,36 months
imp_cuota,360.380,734.380,719.220,688.350,501.370
imp_amortizado,6362.960,24000.000,22000.000,2811.270,2310.490
estado,Charged Off,Fully Paid,Fully Paid,Current,Charged Off
imp_recuperado,0.000,0.000,0.000,0.000,6430.360

In [ ]:
df.dtypes

Conclusiones:

* num_hipotecas, num_lineas_credito, num_cancelaciones_12meses, num_derogatorios, num_meses_desde_ult_retraso deberían ser int
* pero vemos que hay nulos, así que no podemos convertirlas hasta que los imputemos

## VALORES ÚNICOS

### Identificación

In [6]:
df.nunique().sort_values()

id_prestamo                         0
num_cuotas                          2
ingresos_verificados                3
vivienda                            6
num_cancelaciones_12meses           7
rating                              7
estado                              9
antigüedad_empleo                  11
finalidad                          14
num_derogatorios                   17
num_hipotecas                      26
num_lineas_credito                 63
num_meses_desde_ult_retraso       130
porc_tarjetas_75p                 169
tipo_interes                      584
porc_uso_revolving               1097
principal                        1470
dti                              5301
descripcion                      7738
imp_recuperado                  10719
ingresos                        11646
imp_cuota                       33664
empleo                          54437
imp_amortizado                  57838
id_cliente                     140000
dtype: int64

Conclusiones:

* id_prestamo con menos de 2 valores --> eliminar

### Corrección

In [7]:
df.drop(columns = 'id_prestamo', inplace = True)

## DUPLICADOS

### Identificación

In [8]:
df.duplicated(subset='id_cliente').sum()

np.int64(0)

## SEPARAR NUMÉRICAS Y CATEGÓRICAS

### Categóricas

In [9]:
cat = df.select_dtypes(exclude = 'number').copy()

### Numéricas

In [10]:
num = df.select_dtypes(include='number').copy()

## GESTIÓN DE CATEGÓRICAS

### Nulos

#### Identificación

In [11]:
cat.isna().sum().sort_values(ascending = False)

descripcion             132239
empleo                   10261
antigüedad_empleo         9032
rating                       0
ingresos_verificados         0
vivienda                     0
finalidad                    0
num_cuotas                   0
estado                       0
dtype: int64

In [12]:
cat.descripcion.value_counts(dropna=False)

descripcion
NaN                                                                                                                                                                                                                                                                                                                                    132239
                                                                                                                                                                                                                                                                                                                                           13
  Borrower added on 01/26/14 > Debt Consolidation<br>                                                                                                                                                                                                                                                                                       2
  Borrower added on 05/21/13 > Debt consolidation<br>                                                                                                                                                                                                                                                                                       2
  Borrower added on 07/26/13 > Debt Consolidation<br>                                                                                                                                                                                                                                                                                       2
                                                                                                                                                                                                                                                                                                                                        ...
  Borrower added on 06/12/12 > Credit card refinancing<br>                                                                                                                                                                                                                                                                                  1
  Borrower added on 10/16/13 > Loan consolidation<br>                                                                                                                                                                                                                                                                                       1
  Borrower added on 01/13/10 > Steady job required degree and experience for me and my wife. Combined we gross 135,000/year we are able to pay this loan back with no discrepencies.<br/>                                                                                                                                                   1
  Borrower added on 03/17/14 > During my lifetime I've  lived like most Americans. I've borrowed my way to things I believed I needed to impress people I didn't even like. That changed a few years back when I took a class and realized I had to pay off my debt. I want 1 payment but will budget to pay extra on the loan.<br>         1
  Borrower added on 07/01/13 > I want to climb out of debt,so first way to do that is to eliminate as much as I can to lower my monthly payments which I will do with this loan.<br>                                                                                                                                                        1
Name: count, Length: 7739, dtype: int64

In [13]:
cat.empleo.value_counts(dropna=False)

empleo
NaN                                  10261
Teacher                               2459
Manager                               2186
Owner                                 1353
Registered Nurse                       966
                                     ...
FactSet Research Systems, Inc.           1
Federal Security Officer                 1
Technical Service Engineer               1
Social Services Program Manager          1
Sr Risk Adjustment Coding Analyst        1
Name: count, Length: 54438, dtype: int64

In [14]:
cat.empleo.nunique()

54437

In [15]:
cat.antigüedad_empleo.value_counts(dropna=False)

antigüedad_empleo
10+ years    46229
2 years      12607
< 1 year     11717
3 years      11252
1 year        9161
NaN           9032
5 years       8710
4 years       8511
6 years       6313
7 years       5783
8 years       5721
9 years       4964
Name: count, dtype: int64

Conclusiones:

* eliminar descripción y empleo
* imputar nulos de antigüedad_empleo por valor 'desconocido'

#### Corrección

In [16]:
# eliminar descripción y empleo
cat.drop(columns = ['descripcion', 'empleo'], inplace = True)

In [17]:
# imputar nulos de antigüedad_empleo por valor 'desconocido'
cat['antigüedad_empleo'] = cat['antigüedad_empleo'].fillna('desconocido')

## GESTIÓN DE NUMÉRICAS

### Nulos

#### Identificación

In [18]:
num.isna().sum().sort_values(ascending = False)

num_meses_desde_ult_retraso    72007
porc_tarjetas_75p               4606
num_hipotecas                   3051
dti                              106
porc_uso_revolving               101
num_cancelaciones_12meses          8
num_lineas_credito                 2
num_derogatorios                   2
ingresos                           0
id_cliente                         0
principal                          0
tipo_interes                       0
imp_cuota                          0
imp_amortizado                     0
imp_recuperado                     0
dtype: int64

Veamoslas con más detalle.

In [19]:
num.num_meses_desde_ult_retraso.value_counts(dropna=False).sort_index()

num_meses_desde_ult_retraso
0.000        180
1.000        433
2.000        593
3.000        783
4.000        972
           ...
148.000        2
151.000        1
180.000        1
195.000        1
NaN        72007
Name: count, Length: 131, dtype: int64

Hay ceros, pero parecen pocos para una variable que implica retrasos.

Así que vamos a pensar que los nulos significan que no ha habido retrasos.

Y por tanto imputar por ceros.

In [20]:
num.porc_tarjetas_75p.value_counts(dropna=False).sort_index()

porc_tarjetas_75p
0.000      36958
0.170          1
0.250          1
0.400          1
0.500          2
           ...
94.400         3
94.700         1
95.000         1
100.000    23305
NaN         4606
Name: count, Length: 170, dtype: int64

La categoría mayoritaria es cero.

Imputaremos por cero.

In [21]:
num.num_hipotecas.value_counts(dropna=False).sort_index()

num_hipotecas
0.000     57591
1.000     24347
2.000     20181
3.000     14483
4.000      9220
5.000      5362
6.000      2872
7.000      1484
8.000       692
9.000       340
10.000      172
11.000       87
12.000       36
13.000       26
14.000       19
15.000       14
16.000        6
17.000        4
18.000        4
19.000        1
20.000        1
21.000        3
23.000        1
25.000        1
27.000        1
32.000        1
NaN        3051
Name: count, dtype: int64

La categoría mayoritaria es cero.

Imputaremos por cero.

Conclusiones:

* imputar todas por ceros

#### Corrección

In [22]:
num.fillna(0,inplace=True)

Una vez ya imputados los ceros podemos cambiar los tipos a int.

In [23]:
# meter num_hipotecas, num_lineas_credito, num_cancelaciones_12meses, num_derogatorios, num_meses_desde_ult_retraso en una lista y cambiar su tipo a entero
num_imputar_ceros = ['num_hipotecas', 'num_lineas_credito', 'num_cancelaciones_12meses', 'num_derogatorios', 'num_meses_desde_ult_retraso']
num[num_imputar_ceros] = num[num_imputar_ceros].astype(int)

In [24]:
num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140000 entries, 0 to 139999
Data columns (total 15 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id_cliente                   140000 non-null  int64
 1   ingresos                     140000 non-null  float64
 2   dti                          140000 non-null  float64
 3   num_hipotecas                140000 non-null  int64
 4   num_lineas_credito           140000 non-null  int64
 5   porc_tarjetas_75p            140000 non-null  float64
 6   porc_uso_revolving           140000 non-null  float64
 7   num_cancelaciones_12meses    140000 non-null  int64
 8   num_derogatorios             140000 non-null  int64
 9   num_meses_desde_ult_retraso  140000 non-null  int64
 10  principal                    140000 non-null  float64
 11  tipo_interes                 140000 non-null  float64
 12  imp_cuota                    140000 non-null  float64
 13  imp_amortizado               140000 non-null  float64
 14  imp_recuperado               140000 non-null  float64
dtypes: float64(9), int64(6)
memory usage: 16.0 MB

### Atípicos

#### Por desviación típica

##### Identificación


Definir el número de desviaciones típicas

In [29]:
num_desv_tip = 4

Función que devuelve los índices de los atípicos

In [25]:
def atipicos_desv_tip(variable, num_desv_tip = 4):
    #sacamos los nulos por ahora
    variable = variable.dropna()
    #calculamos los límites
    media = np.mean(variable)
    sd = np.std(variable)
    umbral = sd * num_desv_tip
    lim_inf = media - umbral
    lim_sup = media + umbral
    #encontramos los índices de los que están fuera de los límites
    indices = [indice for indice,valor in variable.items() if valor < lim_inf or valor > lim_sup]
    return(indices)

Función que cuenta el número de atípicos

In [26]:
def conteo_atipicos(df,variable, num_desv_tip = 4):
    atipicos = atipicos_desv_tip(df[variable], num_desv_tip)
    return(df.loc[atipicos,variable].value_counts().sort_index())

Variables a aplicar

In [27]:
var_atipicos_dt = ['ingresos','principal','imp_cuota','imp_recuperado']

Obtener los 10 primeros atipicos ordenados en cada variable

In [30]:
for variable in var_atipicos_dt:
    print('\n' + variable + ':\n')
    conteo = conteo_atipicos(num, variable, num_desv_tip)
    print(conteo.sort_index().head(10))

ingresos:

ingresos
415000.000     4
417000.000     1
418000.000     1
420000.000     8
422000.000     1
422550.000     1
423000.000     1
424000.000     1
425000.000    10
430000.000     4
Name: count, dtype: int64

principal:

Series([], Name: count, dtype: int64)

imp_cuota:

imp_cuota
1566.800    1
1587.020    1
1607.800    1
1714.540    1
Name: count, dtype: int64

imp_recuperado:

imp_recuperado
3223.200    1
3223.690    1
3227.430    1
3228.090    1
3228.490    1
3228.600    1
3229.010    1
3229.080    1
3231.980    1
3232.410    1
Name: count, dtype: int64

Revisamos con más detalle la variable ingresos.

In [31]:
num.ingresos.describe()

count     140000.000
mean       78093.824
std        83817.788
min            0.000
25%        46000.000
50%        65000.000
75%        93000.000
max     10999200.000
Name: ingresos, dtype: float64

##### Corrección

Eliminar los registros con ingresos superiores a 400.000$

*Cuidado: Si se eliminan registros hay que eliminarlos tanto de cat como de num*

###### Id de registros a eliminar

In [32]:
a_eliminar = num.loc[num.ingresos > 400000].index.values
a_eliminar

array([   661,   1288,   1734,   2863,   2972,   4043,   4189,   4485,
         4597,   4611,   5272,   6344,   6846,   7152,   7688,   8023,
         8417,   8587,   8767,   8998,  10255,  11095,  11345,  11440,
        11628,  11895,  11994,  12606,  12894,  13003,  13353,  14200,
        14787,  14815,  15567,  15632,  15675,  15987,  16322,  16360,
        16402,  16453,  16740,  16849,  16950,  17027,  17239,  18615,
        19130,  19179,  20494,  20670,  20967,  21022,  21692,  21776,
        21819,  22077,  22611,  22721,  22858,  22896,  23328,  23720,
        24290,  24612,  24831,  24942,  25667,  25709,  25850,  26057,
        26431,  26507,  26765,  27775,  28349,  28559,  28618,  28807,
        29141,  29412,  29942,  30338,  30480,  31121,  31157,  31617,
        31770,  31925,  32865,  33601,  33794,  35073,  35348,  35692,
        36578,  36845,  37278,  37305,  37951,  38585,  38950,  39520,
        42323,  42589,  42590,  42680,  42808,  42962,  42997,  43288,
        43395,  43873,  45351,  45805,  46576,  46856,  47393,  49355,
        49788,  49816,  50138,  50736,  51142,  51696,  51948,  52085,
        52353,  52578,  52839,  53145,  53391,  53402,  53563,  53571,
        53963,  55216,  55446,  56073,  56359,  56949,  57345,  57358,
        57701,  57916,  58536,  58777,  58784,  58933,  58985,  59035,
        59074,  59721,  59960,  60031,  60765,  61348,  61423,  61545,
        61769,  61907,  62271,  62553,  62590,  62696,  63015,  63622,
        63790,  64124,  64441,  64509,  65168,  65507,  65897,  66958,
        68292,  68957,  69460,  70021,  70845,  71229,  71771,  71836,
        71973,  72021,  72343,  72593,  72619,  73082,  73747,  74143,
        74393,  74842,  75528,  75791,  75933,  75999,  76260,  76299,
        76846,  77975,  78536,  78904,  80196,  81102,  81115,  82035,
        82377,  82575,  82635,  83485,  83618,  83716,  83720,  83775,
        83823,  84174,  84375,  84694,  85003,  85402,  85536,  85952,
        86083,  86380,  86614,  86648,  87118,  87589,  87883,  88836,
        89155,  89217,  89473,  91002,  91055,  91236,  91302,  91409,
        91880,  93095,  93359,  93540,  93803,  94472,  94823,  95488,
        95534,  95824,  95925,  96514,  96573,  96755,  96910,  97023,
        97258,  97642,  97716,  97741,  97993,  98028,  98031,  98102,
        98288,  98448,  98480,  98612,  99312,  99872,  99928, 101013,
       101229, 101289, 101923, 101968, 103096, 103608, 103683, 103706,
       104553, 105313, 105725, 106092, 106458, 106895, 106927, 106971,
       106987, 107102, 107179, 108745, 109076, 109352, 109401, 109530,
       109651, 110007, 111314, 111496, 111682, 112274, 112510, 112940,
       113020, 113303, 113566, 113798, 114083, 114197, 114501, 114645,
       114662, 114806, 114905, 115248, 115665, 116384, 116663, 117058,
       117351, 117452, 119098, 119343, 120397, 120450, 120718, 120837,
       120918, 121172, 122052, 122119, 122323, 122544, 123607, 123770,
       123824, 123948, 123949, 124297, 124787, 124887, 125029, 125070,
       125550, 126314, 126389, 126390, 126399, 126944, 127297, 127427,
       127686, 128312, 128662, 128900, 129060, 129133, 129385, 129757,
       129805, 130000, 130174, 130429, 130690, 130954, 131425, 131487,
       132110, 132544, 132593, 132956, 133362, 133526, 134177, 134405,
       134500, 135341, 135830, 136284, 136573, 137031, 137109, 137302,
       137604, 137738, 138334, 138789, 139633, 139657])

###### Aplicar

In [33]:
cat = cat[~cat.index.isin(a_eliminar)]
num = num[~num.index.isin(a_eliminar)]

## GUARDAR DATASETS TRAS CALIDAD DE DATOS

Guarda los avances en df, cat y num con un sufijo para poder guardar o recuperar avances del proyecto.

En formato pickle para no perder las modificaciones de metadatos.

In [34]:
df.to_pickle('../02_datos/03_Entrenamiento/train_calidad.pkl')
cat.to_pickle('../02_datos/03_Entrenamiento/cat_calidad.pkl')
num.to_pickle('../02_datos/03_Entrenamiento/num_calidad.pkl')